### ISSUE TITLE
sdist on pypi

### ISSUE THREAD

**Issue by millsks** [mike-huls/bloomlib#1]
Thanks for the work on bloomlib.  We wanted to install it with conda, but there isnt a feedstock for bloomlib yet.  I tried to create one, but getting the following error when I try to create the recipe with grayskull.  Is it possible for you to upload the tarball to PyPI in addition to the wheel?

```
#### Initializing recipe for bloomlib (pypi) ####

Recovering metadata from pypi...
Traceback (most recent call last):
  File "/home/millsks/UserLocal/mambaforge/bin/grayskull", line 10, in <module>
    sys.exit(main())
  File "/home/millsks/UserLocal/mambaforge/lib/python3.9/site-packages/grayskull/main.py", line 276, in main
    generate_recipes_from_list(args.pypi_packages, args)
  File "/home/millsks/UserLocal/mambaforge/lib/python3.9/site-packages/grayskull/main.py", line 299, in generate_recipes_from_list
    recipe, config = create_python_recipe(
  File "/home/millsks/UserLocal/mambaforge/lib/python3.9/site-packages/grayskull/main.py", line 334, in create_python_recipe
    GrayskullFactory.create_recipe(
  File "/home/millsks/UserLocal/mambaforge/lib/python3.9/site-packages/grayskull/base/factory.py", line 46, in create_recipe
    GrayskullFactory.REGISTERED_STRATEGY[repo_type.lower()].fetch_data(
  File "/home/millsks/UserLocal/mambaforge/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 60, in fetch_data
    update_recipe(recipe, config, sections or ALL_SECTIONS)
  File "/home/millsks/UserLocal/mambaforge/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 485, in update_recipe
    metadata = get_metadata(recipe, config)
  File "/home/millsks/UserLocal/mambaforge/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 347, in get_metadata
    sdist_metadata, pypi_metadata = get_origin_wise_metadata(config)
  File "/home/millsks/UserLocal/mambaforge/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 231, in get_origin_wise_metadata
    pypi_metadata = get_pypi_metadata(config)
  File "/home/millsks/UserLocal/mambaforge/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 274, in get_pypi_metadata
    raise AttributeError(f"There is no sdist package on pypi for {config.name}.")
AttributeError: There is no sdist package on pypi for bloomlib.
```

**Comment by mike-huls** [comment]
Hello millsks, 
I've created and uploaded the tarball

**Comment by millsks** [comment]
Thanks.  Looks good now!

```
(base) millsks@ATREIDES:~/UserLocal/repos/staged-recipes/recipes$ grayskull pypi bloomlib
#### Initializing recipe for bloomlib (pypi) ####

Recovering metadata from pypi...
Starting the download of the sdist package bloomlib
bloomlib 100% Time:  0:00:00 144.2 KiB/s|###################################################################################################################################################################################################################################################################################################################################################|
Checking for pyproject.toml
pyproject.toml found in /tmp/grayskull-bloomlib-y0us3w3r/bloomlib-0.0.2/pyproject.toml
Recovering information from setup.py
Executing injected distutils...
Checking >> python 100% |############################################################################################################################################################################################################################################################################################################################################|[Elapsed Time: 0:00:00]
Recovering license info from spdx.org ...
Matching license file with database from Grayskull...
Match percentage of the license is 98%. Low match percentage could mean that the license was modified.
License type: MIT
License file: ['LICENSE.txt']
Build requirements:
  <none>
Host requirements:
  - python >=3.9
  - maturin >=1.4,<2.0
  - pip
Run requirements:
  - python >=3.9

RED: Missing packages
GREEN: Packages available on conda-forge
Using default recipe maintainer: AddYourGitHubIdHere

Maintainers:
   - AddYourGitHubIdHere

#### Recipe generated on /home/millsks/UserLocal/repos/staged-recipes/recipes for bloomlib ####
```
